### ISSUE TITLE
Does not work on README example grammar.js

### ISSUE THREAD

**Issue by Meai1** [tree-sitter/tree-sitter-cli#18]
First error are missing colons on line 30 and 32

But then when I fix that, I still get:

> [pc@localhost tree-sitter-test]$ tree-sitter generate grammar.js 
> Error: Unresolved conflict for symbol sequence:
> 
>   expression  '^'  expression  •  '^'  …
> 
> Possible interpretations:
> 
>   1:  (expression  expression  '^'  expression)  •  '^'  …
>   2:  expression  '^'  (expression  expression  •  '^'  expression)
> 
> Possible resolutions:
> 
>   1:  Specify a left or right associativity in `expression`
>   2:  Add a conflict for these rules: `expression`
> 

I just got started with this repo, I dont have a clue what to do to fix this.
Can you add comments on every line of the grammar.js telling us what it is doing? I dont even know from the repo description for what language this grammar is supposed to be, so that makes it even harder to understand.

**Comment by tclem** [comment]
Hi @Meai1, you're correct that the README example isn't working! I just pushed a fix in a6258852d2284a0b62e5cb64ace98e96dc4d9df4 that brings it up-to-date.

> I dont even know from the repo description for what language this grammar is supposed to be, so that makes it even harder to understand.

The example grammar looks like it's for a small, toy language that allows basic assignment and expressions. For example, this should be valid code (and should parse once you get the grammar generating and compiling):

`test.txt`
```
# comment
foo = 1 + 2;
```

If you're looking for a more full feature example of commonly used programming languages (as well as how to structure a project), you might want to check out [tree-sitter-go](https://github.com/tree-sitter/tree-sitter-go), [tree-sitter-javascript](https://github.com/tree-sitter/tree-sitter-javascript), or [tree-sitter-ruby](https://github.com/tree-sitter/tree-sitter-ruby).

**Comment by maxbrunsfeld** [comment]
:+1: Thanks for pointing that out, @Meai1.

**Comment by Meai1** [comment]
Can you explain also how to read the error syntax? What does the • and the  … mean?

`Compilation failed: Unresolved conflict for symbol sequence:

  expression_repeat1  •  '+'  …

Possible interpretations:

  1:  expression_repeat1  (expression)  •  '+'  …
  2:  (expression  expression_repeat1)  •  '+'  …

Possible resolutions:

  1:  Add a conflict for these rules: `expression`
`

I'm trying to recreate the grammar.js sample in the .json format from the original tree-sitter repo because I dont want to learn a different syntax that I cant use with the original library anyway.
This is the file that produces the error, I only added the REPEAT (note: not REPEAT1) section.

`{
      "name": "arithmetic",
      "extras": [
        {"type": "PATTERN", "value": "\\s"},
        {"type": "SYMBOL", "name": "comment"}
      ],

      "rules": {

        "expression" : {
        "type": "REPEAT",
        "content":
            { "type" : "SYMBOL", "name": "choice"}
        },

        "choice": {
          "type": "CHOICE",
          "members": [
            {"type": "SYMBOL", "name": "sum"},
            {"type": "SYMBOL", "name": "product"},
            {"type": "SYMBOL", "name": "number"},
            {"type": "SYMBOL", "name": "variable"},
            {
              "type": "SEQ",
              "members": [
                {"type": "STRING", "value": "("},
                {"type": "SYMBOL", "name": "expression"},
                {"type": "STRING", "value": ")"}
              ]
            }
          ]
        },

        "sum": {
          "type": "PREC_LEFT",
          "value": 1,
          "content": {
            "type": "SEQ",
            "members": [
              {"type": "SYMBOL", "name": "expression"},
              {"type": "STRING", "value": "+"},
              {"type": "SYMBOL", "name": "expression"}

            ]
          }
        },

        "product": {
          "type": "PREC_LEFT",
          "value": 2,
          "content": {
            "type": "SEQ",
            "members": [
              {"type": "SYMBOL", "name": "expression"},
              {"type": "STRING", "value": "*"},
              {"type": "SYMBOL", "name": "expression"}
            ]
          }
        },

        "number": {"type": "PATTERN", "value": "\\d+"},
        "comment": {"type": "PATTERN", "value": "#.*"},
        "variable": {"type": "PATTERN", "value": "[a-zA-Z]\\w*"}
      }
}
`
