### ISSUE TITLE
Can’t parse a bunch of files at once

### ISSUE THREAD

**Issue by robrix** [tree-sitter/tree-sitter-cli#23]
tree-sitter-ruby runs against a bunch of examples, but [has to do that by shelling out to tree-sitter-cli for each file individually](https://github.com/tree-sitter/tree-sitter-ruby/blob/master/script/parse-examples#L5). It’d be nice if tree-sitter-cli could parse a whole list of files in a single run.

**Comment by Pike** [comment]
This was fixed in 10b343eed6b5b0896c6b25ce51ba9328ac393c64.

**Comment by robrix** [comment]
Oh, indeed it was! Nice catch @Pike.
