### ISSUE TITLE
Which version should I stick to?

### ISSUE THREAD

**Issue by banacorn** [tree-sitter/tree-sitter-cli#37]
Packages such as [tree-sitter-python](https://github.com/tree-sitter/tree-sitter-python/blob/master/package.json#L16) and [tree-sitter-ruby](https://github.com/tree-sitter/tree-sitter-ruby/blob/master/package.json#L18) have upgraded to `tree-sitter-cli@0.13.x`. I've also upgrade [tree-sitter-agda](https://github.com/tree-sitter/tree-sitter-agda/blob/master/package.json#L29) to `tree-sitter-cli@0.13.x` and published it. 

Everything looks fine ... until I switched to the development mode on `Atom 1.29.0` , where I would get error messages like:
```
RangeError: Incompatible language version. Expected 8. Got 9
```

I've [encountered this problem before](https://github.com/tree-sitter/tree-sitter/issues/151) and I've noticed that Atom 1.29.0 is using `tree-sitter-cli@0.12.12`. So as I downgraded my `tree-sitter-cli` to `0.12.12`, the incompatible language version problem went away as expected.

However, I still have a few questions: 
* Why is `tree-sitter-cli@0.13.x` working fine in production mode but not in development mode?
* Which version of `tree-sitter-cli` should I stick to? 
  1. The version that the latest stable Atom release is using, such as `0.12.12` in this case 
  2. The version that other tree-sitter languages are using, such as `0.13.x` in this case

**Comment by Aerijo** [comment]
If this is about Atom, see https://github.com/atom/atom/issues/17777

**Comment by banacorn** [comment]
Thank you @Aerijo, it definitely has something to do with Atom's versions.

But this is what is confusing me:
* Atom 1.29 production mode: works with `tree-sitter@0.13.x`
* Atom 1.29 development mode: works with `tree-sitter@0.12.x`

Why?

**Comment by maxbrunsfeld** [comment]
> But this is what is confusing me:
> Atom 1.29 production mode: works with tree-sitter@0.13.x
> Atom 1.29 development mode: works with tree-sitter@0.12.x

I don't think that's true. Dev mode has nothing to do with the Tree-sitter ABI version. It's probably just that when you're running Atom in `--dev` mode, it's probably running different code than what's in Atom 1.29.

@banacorn I'm going to close this out since it's about Atom. If you have further questions, see the issue that @Aerijo mentioned.
