### ISSUE TITLE
Generate and install required for each test

### ISSUE THREAD

**Issue by superlou** [tree-sitter/tree-sitter-cli#43]
I'm not sure if this is intentional behavior or not. In order for `test` to reflect grammar updates, I always have to run the following:

```
tree-sitter generate
npm install
tree-sitter test
```

This works just fine, but I was wondering if there is something I missed in my environment setup (Linux Mint 18.3, npm 6.4.1) that saves having to run all three commands (or make a script to do so). I get the same effect using `node-gyp`. Is this the expected testing workflow?

**Comment by Aerijo** [comment]
Try `tree-sitter generate` followed by `node-gyp rebuild`. Both are needed if you want to test a change.

This can be made a shortcut in the `package.json`
```
"scripts": {
    "build": "tree-sitter generate && node-gyp build",
    "install": "prebuild-install || node-gyp rebuild",
    "pre-build": "prebuild --all --strip --verbose",
    "pre-build:upload": "prebuild --upload-all",
    "test": "tree-sitter test && tree-sitter parse examples -q -t"
  }
```
(Subtle hint to set up CI deployment too, for the users who don't have build tools).

To build, use `npm run build`.

**Comment by maxbrunsfeld** [comment]
Yeah, `node-gyp build` is faster than `npm install`. But other than that, that is the expected workflow.

And 👍 for the suggestion of defining that `build` entry in your `scripts`. Maybe we should define a command like that as part of `tree-sitter-cli` itself? Not sure if that'd be helpful.

**Comment by Aerijo** [comment]
@maxbrunsfeld `tree-sitter build`

**Comment by superlou** [comment]
That makes sense. My package.json has:

```
"scripts": {
    "test": "tree-sitter generate && node-gyp build && tree-sitter test"
  },
```

It's mostly for convenience of being able to just press "up" and enter in the terminal between changes. A `tree-sitter build` as suggested by @Aerijo does seem to make sense if `node-gyp` is very strongly recommended. Do we want to close this issue, or leave it open to discuss adding a faster build/test command to the CLI?
